server:
  port: 2222

spring:
  application:
    name: service-provider
eureka:
  client:
    healthcheck:   # 配置开启健康检查
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ # 指定注册中心的地址
  instance:
    # IP地址优先
    preferIpAddress: true
    # 按需配置续约更新时间和到期时间
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
