server:
  port: 3333
spring:
  application:
    name: consumer-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/ # 指定注册中心的地址
  instance:
    # IP地址优先
    preferIpAddress: true